//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IBrowserConsoleAdapter
{
    logAsync(message: string) : Promise<void>;
}
export interface IPointerEventsAdapterHandler
{
    handleClickAtAsync(x: number, y: number) : Promise<void>;
}
export interface IPointerEventsAdapter
{
    addForHandlerAsync<THandler>(handlerReference: DotNet.DotNetObject) : Promise<void>;
}
